### ISSUE TITLE
Conversion errors with 0.1.143

### ISSUE THREAD

**Issue by Elrondolio** [maxton/LibForge#19] opened 2018-12-28 18:33 UTC
Hey Maxton,

Don't know if this is the appropriate place for this but thought it might be useful to share my experience with ForgeTool v0.1.143.  I have attempted to convert 316 customs and have had 246 successes. Thats almost a 78% success rate.  Thank you so very much for this wonderful tool - myself, my 2 children and my wife have LOVED playing some of these new tracks in RB4.

Of the other 70 customs that did not convert properly: 25 erred during conversion, 41 converted fine and installed as packages fine on my PS4 but crash RB4 when attempting to play and 4 more play fine but are mislabeled as the wrong artists.  I created a quick batch file to test conversions of customs quickly and log results to better understand the issues.  I thought you might want a copy of these customs and log files as it might help you track down any remaining issues with ForgeTool.

You can access the customs that error, logs and text of successful conversions here:
http://tribewalker.com/forgetool/rock_band_customs_errors_with_forgetool_0.1.143.zip

Again, just wanted to thank you for what you are doing with the PS4 and Rock Band 4 in particular.  If this is an inappropriate place to post like this, please delete at your discretion.  Merry Christmas and have a happy new year!

- Elrondolio

**Comment by maxton** [comment] 2018-12-28 19:07
Thanks for the report, the more failures I can check, the better conversions will get. So I appreciate the time you've taken to test all of these.

The ones which fail to convert entirely are the easiest to fix, so I'll probably work on fixing those first. The ones which crash RB4 are trickier, but hopefully they will get fixed with other general improvements made to the conversion process. The 4 that are mislabeled as the wrong artist are the most surprising, as the artist data should be coming directly from the DTA, same as RB3!

I'll look through these and create more specific issues if I can track down what's causing the failures.

**Comment by maxton** [comment] 2018-12-29 17:00
Ok, I made a list of the unique errors and checked off the ones I fixed so far:

### Conversion errors
- [x] Index was outside the bounds of the array (Lipsync)
- [x] Index and length must refer to a location within the string (ID generation)
- [x] Unhandled midi note 115 in drum track (MIDI conversion)
- [x] Index was outside the bounds of the array (Texture conversion)
- [ ] Texture was not 512x512 or 256x256 (Texture conversion)
- [ ] Offset and length were out of bounds for the array... (PKG.KeysEntry)
- [ ] Length of the data to encrypt was invalid (PKG.PkgWriter.WriteBody)

### Loading errors
- [x] Shortname collisions (mislabeling)
- [x] Case sensitivity problems (crashes)

**Comment by maxton** [comment] 2018-12-29 17:37
@Elrondolio I think these should all convert now (some may not have album artwork after conversion, yet). The one error I couldn't reproduce is the one you got with Pearl Jam - Yellow Ledbetter, so maybe that was a one-off issue with your PC?

**Closed by maxton** 2018-12-29 17:37 UTC

**Comment by Elrondolio** [comment] 2018-12-30 01:34
Wow, @maxton that was very quick and very thourough work.  Thank you!  I haven't played through all of them of course but they all convert and, indeed, load properly now.  That includes Yellow Ledbetter so it must have been my system on that one.

Thanks again for enabling such a huge part of my family's PS4 enjoyment.  I'll keep downloading and testing new customs and let you know if I run across any other issues.  Happy new year!
